name: cats_fact
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  translator: ^0.1.7
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  retrofit: ^3.0.1+1   
  json_annotation: ^4.6.0
  appinio_swiper: ^1.1.0
  dio: ^4.0.6
  intl: ^0.17.0
  flutter_launcher_icons: ^0.10.0
  meta: ^1.8.0
  lottie: ^2.2.0
  share_plus: ^6.3.0
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  google_sign_in: ^6.0.1
  cloud_firestore: ^4.4.3
  uuid: ^3.0.7

dev_dependencies:
  hive_generator: ^1.1.3
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.4.0
  flutter_lints: ^2.0.0
  
flutter_icons:
  android: true
  ios: true 
  image_path: "assets/logo.png"


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/46864-lovely-cats.json
    - assets/91743-fat-cat-wants-to-chat.json
    - assets/67834-ssssttt-shut-up-the-cat-is-sleeping (1).json
    - assets/20894-lazy-cat.json
