// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7gX-EJOZ-n_TmTKCqp3V3hlB-NG30AOo',
    appId: '1:723027032206:android:28a962a8897067a51631df',
    messagingSenderId: '723027032206',
    projectId: 'cat-facts-b0e55',
    databaseURL: 'https://cat-facts-b0e55-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cat-facts-b0e55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3BB08WO2NLF26QMqM8SGHazqK6ZwrtTk',
    appId: '1:723027032206:ios:e5961daaf7f466ca1631df',
    messagingSenderId: '723027032206',
    projectId: 'cat-facts-b0e55',
    databaseURL: 'https://cat-facts-b0e55-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cat-facts-b0e55.appspot.com',
    iosClientId: '723027032206-ej1jc38lbqso8r2lfad7i28jjd9dv73s.apps.googleusercontent.com',
    iosBundleId: 'com.example.catsFact',
  );
}
